# Base de datos
spring.datasource.url=${DB_URL:jdbc:h2:mem:nexoradb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${DB_USERNAME:nexora_admin}
spring.datasource.password=${DB_PASSWORD:Nexora2024!Secret}


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:create-drop}
spring.jpa.show-sql=${SQL_SHOW:true}
spring.jpa.properties.hibernate.format_sql=${SQL_FORMAT:true}

spring.h2.console.enabled=${H2_CONSOLE:true}
spring.h2.console.path=/h2-console

nexora.external.notification-url=${NOTIFY_URL:https://notify.nexora.com/api/v2}
nexora.external.api-key=${API_KEY:sk-dev-default-key}
nexora.external.erp-endpoint=${ERP_ENDPOINT:https://erp.nexora.internal/sync}
nexora.external.auth-secret=${AUTH_SECRET:dev-secret-key}

server.port=${SERVER_PORT:8082}
