# Base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:nexoradb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=nexora_admin
spring.datasource.password=Nexora2024!Secret

# Consola H2 (solo para desarrollo)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Servicios externos
nexora.external.notification-url=https://notify.nexora.com/api/v2
nexora.external.api-key=sk-prod-nxr-7f8a9b0c1d2e3f4a5b6c
nexora.external.erp-endpoint=https://erp.nexora.internal/sync
nexora.external.auth-secret=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.superSecretValue

server.port=8082
