apiVersion: v1
kind: ConfigMap
metadata:
  name: config-nexora-api-qa
  namespace: nexora-qa
data:
  # Servidor y H2
  SERVER_PORT: "8082"
  H2_CONSOLE: "true"

  # Base de datos
  DB_URL: "jdbc:h2:mem:nexoradb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
  DB_DDL_AUTO: "create-drop"
  SQL_SHOW: "true"
  SQL_FORMAT: "true"


  NOTIFY_URL: "https://notify.nexora.com/api/v2"
  ERP_ENDPOINT: "https://erp.nexora.internal/sync"